version: '3.8'

services:
  locker_api:
    image: locker_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json
    env_file:
      - .env
      

