version: '3.8'

services:
  locker_api:
    image: locker_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - ./config.json:/app/config.json
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8000}

